### ISSUE TITLE
Make threedots and metadata buttons always visible on touchscreens

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#155]
In normal operation, mousing over a cover darkens it and causes the metadata button (lower left) and threedot menu button (lower right) appear. If you don't have a mouse, though (because, say, you're using codex on a touchscreen). you can't hover and have to guess where they are.

Experimenting with CSS injection I've settled on this for my own install, which makes them always visible (without darkening the cover overall) and puts each one inside a translucent black circle so that it remains visible against lighter covers. There is undoubtedly a more elegant way to do this server-side.

```css
@media (hover: none) {
  /* Metadata and menu buttons are always visible when using a touchscreen. */
  div.cardCoverOverlayBottomRow {
    opacity: 1.0 !important;
  }

  /* And put them in a black circle so we can see them even against light covers,
     since we don't get the darkening of the whole cover without hovering. */
  div.cardCoverOverlayBottomRow button {
    border-radius: 2em;
    background: black;
    opacity: 0.6;
  }
}
```
