### ISSUE TITLE
Feature request: enlarge-to-screen setting

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#167]
For most professionally produced comics the main problem is the pages being *larger* than the screen, but there's a lot of indie stuff, archived webcomics, old scanlations, etc that is drawn or scanned at a lower resolution and is smaller than the screen size on modern displays. When viewing these in Codex it results in a small page floating in a sea of blackness. It would be nice to have an option in Codex to enlarge these to the screen.

The following CSS is not production-ready and won't work on PDFs, but accomplishes this for CBZs by hijacking the existing "fit to" logic to expand small images as well as shrinking large ones:

```css
img.page.fitToScreen {
  height: 100vh;
  width: 100vw;
  object-fit: contain;
}

img.page.fitToHeight {
  height: 100vh;
  object-fit: contain;
}

img.page.fitToWidth {
  width: 100vw;
  object-fit: contain;
}

```
