### ISSUE TITLE
OPDS-PS not working with Panels

### ISSUE THREAD

**Issue by timvancann** [ajslater/codex#328]
Streaming comics using the iOS app Panels (and Chunky) using OPDS work fine, but the page (and completion) progress is not retained server-side even though it should be supported: https://github.com/ajslater/codex#supported-opds-specifications

Running on Docker, version 1.4.2.

**Comment by timvancann** [comment]
After a bit more investigation it turns out I wasn't logged in in Panels, and since Codex syncs progress per user I attempted to log in over OPDS. But logging in doesn't connect to the OPDS service at all.

A possible similar bug is already posted here: https://github.com/ajslater/codex/issues/310

**Comment by ajslater** [comment]
I'm having some trouble replicating this on iOS Panels.
In the Library settings for my connection to Codex (Panels->LIbrary->Libraries->Codex->Configure) I have filled in:
```yaml
Alias: Codex
Host: http://my.codex.server/opds/v1.2/r/0/1
Port: 9810
Username: aj
Password: verysecretpassword
```

I browse and open a comic. 
Read forward 10 pages. 
Close Panels Completely. 
Reopen Panels. 
Browse and open the same comic.
It opens to page 10.
